name: Xcitepictures
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131716'
    - '#d4bbb9'
    - '#e27581'
    - '#555034'
    - '#b02838'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
